### ISSUE TITLE
OpenOCD-Vexriscv: Additional Prerequisite

### ISSUE THREAD

**Issue by ThorKn** [sea212/QuantumRisc-VM-Build-Tools#1]
Error description:
Build stops with error, asking for a non-excisting yaml-file.

Solution:
It seems that OpenOCD Vexriscv recently added a new prerequisite library:
libyaml-dev
This library must be added to the essentials-script.

Source:
README of the OpenOCD-Vexriscv repo. https://github.com/SpinalHDL/openocd_riscv

**Comment by sea212** [comment]
Thanks for noting!

Fixed in 3f0a96fb7b5754a999aaf853641022895caba48d
