### ISSUE TITLE
Download location of the VM

### ISSUE THREAD

**Issue by ThorKn** [sea212/QuantumRisc-VM-Build-Tools#14]
So far the VM download (11 GB) is hosted on Random-Orcales.org.
This might be a bottleneck in near (and far) future.
We've talked about moving the Download-File to somewhere else.

Hosting at HSRM or decentralized hosting (IPFS, Torrent) are current options.

Some events in the near future (SpinlHDL Workshops, Journal-articles, Research Collabs, Twitter influencers) could drive the download counts up. We should discuss and set the download location soon!

Needed:
Discussion between Harald, Steffen and Thorsten

**Comment by sea212** [comment]
VMs are also hosted on HSRM servers now.
