### ISSUE TITLE
iceprog permission problem

### ISSUE THREAD

**Issue by SteffenReith** [sea212/QuantumRisc-VM-Build-Tools#19]
It seems that iceprog only works as root. Maybe the udev-rules have to be fixed.

**Comment by sea212** [comment]
Thanks for mentioning this. I remember that we already have talked about this two months ago. After our conversation and before this project was migrated to GitHub, I have implemented the inclusion of device exceptions (GitLab commit hash 2556c1c194ee26e3780deb1ba9c01fbfd6d60a1d)
