### ISSUE TITLE
Support for Rust

### ISSUE THREAD

**Issue by SteffenReith** [sea212/QuantumRisc-VM-Build-Tools#23]
Maybe it is possible to add support for RISCV-Rust.

**Comment by sea212** [comment]
@SteffenReith I am not quite sure what has to be done here. Official risc-v support for the default extension set was added in 2019, one can add the target using the command `rustup target add riscv64-unknown-none-elf`. Using a feasible configuration, one can compile the code for riscv64gc-unknown-none-elf. There is also a create for [low-level access for RiscV-CPUs](https://github.com/rust-embedded/riscv). Do you suggest to install the rust toolchain, add the riscv target and install some useful riscv creates like the low-level access crate?
