### ISSUE TITLE
RISC-V Tools (GCC, etc.): Path in '.profile'?

### ISSUE THREAD

**Issue by ThorKn** [sea212/QuantumRisc-VM-Build-Tools#3]
The GCC tools get installed into the proper location 'opt/riscv/bin/'.
But the path doesn't get set in the '.profile' file.

Generally the script for the GCC tools doesn't have the '-i" option and neither the INSTALL variable. Why?

**Comment by sea212** [comment]
The default behaviour of the script is to export the path within /etc/profile, if no user was specified using the _-u_ parameter. If a user was specified, the export is stored in the .profile file within the users home directory.

During my local tests both scenarios have worked as expected. Please report here if you experience issues with this functionality.

**Comment by ThorKn** [comment]
This might be the (so far) only difference between the script-installs on Ubuntu and Linux Mint. This behaviour was observed on Linux Mint 20 (Cinnamon). I will give it a try on a freshly Ubuntu 20.04 next week, when i'm back from Bochum.
