### ISSUE TITLE
Multi-threaded build

### ISSUE THREAD

**Issue by 614n** [sea212/QuantumRisc-VM-Build-Tools#4]
Check that make uses `-j$(nproc)` (or similar) where possible (we found that it is used already very often, but it would be nice to keep the eyes open whether it is missing somewhere).

**Comment by sea212** [comment]
Thanks for noting. I paid attention to include this everywhere, so that the scripts use all cores if possible.

 @.Everybody Feel free to indicate `make` calls that miss the `-j$(nproc)` flag here, or even create pull requests which already append the missing flag to the invocation of `make`
