### ISSUE TITLE
Yosys: 'GitHub Master' instead of 'lastest release'

### ISSUE THREAD

**Issue by ThorKn** [sea212/QuantumRisc-VM-Build-Tools#5]
Please change:
The default installation of Yosys must come from the Github Master.

Reason:
Nextpnr-ecp5 needs the most actual version of yosys.

Behaviour at the moment:
Right now the lastest release (0.9) of Yosys gets installed by default.

**Comment by sea212** [comment]
I suggest to introduce new values for the tag _-t_ flag:

- default/latest = latest commit in default branch
- stable = latest tag (needs check if tags are obsolescent) [this is currently the default behaviour]
- custom branch name, tag name or commit hash (already available)
